= Guided solution (page 1 of 2)

*ISSUE* +
- # hammer ping fails with: +
----
candlepin:        
    Status:          FAIL 
    Server Response: Message: Failed to open TCP connection to localhost:23443 (Connection refused - connect(2) for "localhost" port 23443) 
candlepin_auth:   
    Status:          FAIL 
    Server Response: Message: A backend service [ Candlepin ] is unreachable 
candlepin_events: 
    Status:          FAIL 
    message:         Not running 
----

- Widgets on satellite web ui are not loading properly. +
- messages show the below which indicates issue with making connections to db as well +
FATAL:  remaining connection slots are reserved for non-replication superuser connections

- Checking the parameters in `/etc/foreman-installer/scenarios.d/satellite-answers.yaml` we can see the below parameters misconfigured: +
----
foreman-foreman-service-puma-threads-min=300 
foreman-foreman-service-puma-threads-max=300
foreman-foreman-service-puma-workers=120
foreman-db-pool=300
foreman-proxy-content-pulpcore-worker-count=10
----

*FIX* +
According to official doc for performance tuning of Satellite 6.15 for system with 64GB RAM and 8 VCPUs we should have: +

- medium tuning profile should be selected +
- Recommended Puma Threads for both min & max is 16 +
- Recommended Puma Workers is 8 – 12 +
- Value for pulpcore worker should be max 8 +
- The effective value of $db_pool is automatically set to equal $foreman::foreman_service_puma_threads_max +

Combining the above we may run: +
`# satellite-installer --foreman-foreman-service-puma-threads-min=16 --foreman-foreman-service-puma-threads-max=16 --foreman-foreman-service-puma-workers=12 --foreman-db-pool=16 --foreman-proxy-content-pulpcore-worker-count=8 --tuning medium`
