= Guided Solution (page 1 of 2)
:experimental:

== Objectives

* Investigate why web ui is not accessible and satellite becomes unresponsive occasionally in Red Hat Satellite 6.
* Investigate why widgets on Satellite web ui are not loading.
* Investigate why candlepin is down and some commands may fail to execute.
* Solve the functionality and performance issues in the hands-on lab environment.

== Instructions

Run following instructions on `satellite` system with `root` as user.

.Sample output:
----
[ec2-user@satellite ~]$ sudo su -
[root@satellite ~]#
----

. Run `hammer ping` command.
+
[source,bash,role=execute]
----
hammer ping
----
+
.Sample output:
----
candlepin:
    Status:          FAIL
    Server Response: Message: Failed to open TCP connection to localhost:23443 (Connection refused - connect(2) for "localhost" port 23443)
candlepin_auth:
    Status:          FAIL
    Server Response: Message: A backend service [ Candlepin ] is unreachable
candlepin_events:
    Status:          FAIL
    message:         Not running
----

Also

- Widgets on `satellite web ui` [the page presented after logging into satellite] are not loading properly. +
- `/var/log/messages` show the below which indicates issue with making connections to db as well
+
.Sample Output:
----
FATAL:  remaining connection slots are reserved for non-replication superuser connections
----

- Checking the parameters in `/etc/foreman-installer/scenarios.d/satellite-answers.yaml` we can see the below parameters misconfigured: +
----
foreman_foreman_service_puma_threads_min: 300 
foreman_foreman_service_puma_threads_max: 300
foreman_foreman_service_puma_workers: 120
db_pool: 300
foreman_proxy_content_pulpcore_worker-count: 10
----

According to official doc for performance tuning of Satellite 6.15 for a system with 64GB RAM and 8 VCPUs we should have: +

- medium tuning profile should be selected +
- Recommended Puma Threads for both min & max is 16 +
- Recommended Puma Workers is 8 – 12 +
- Value for pulpcore worker should be max 8 +
- The effective value of $db_pool is automatically set to equal $foreman::foreman_service_puma_threads_max +

Combining the above we may run:

[source,bash,role=execute]
----
satellite-installer --foreman-foreman-service-puma-threads-min=16 --foreman-foreman-service-puma-threads-max=16 --foreman-foreman-service-puma-workers=12 --foreman-db-pool=16 --foreman-proxy-content-pulpcore-worker-count=8 --tuning medium
----