= What’s in this break-fix?

== In this break-fix:

**Type of issue:**

The provided Satellite server has been reported to have issues like:

- Web ui is not accessible and satellite becomes unresponsive occasionally
- Widgets on Satellite web ui are not loading
- Candlepin is down and some commands may fail to execute

**What you should already know:**

- A Red Hat Certified System Administrator (RHCSA) or have equivalent experience administrating Red Hat Enterprise Linux 7 or 8.
- Administering Red Hat Satellite 6

**How break-fix training works:**

. Challenge yourself in the break-fix activity. It describes a problem scenario that's simulated in the lab environment where you can investigate and solve the problem.
. Follow up with the guided solution:
.. If you weren't able to solve the problem on your own, read and follow the instructions in the Guided Solution to complete this training.
.. If you were successful in solving the problem, read the solution for useful tips you can apply when solving similar problems.