= Break-fix Scenario

The provided satellite server has been reported to have few issues.
The satellite web ui is not accessible and satellite becomes unresponsive occasionally.
Widgets on satellite web ui are not loading.
Candlepin is down and some commands may fail to execute.
Fixing certain parameters in satellite and using an appropriate tuning profile should be done to restore functionality and optimize performance.
You may need to reboot the satellite from web ui of lab interface in case it becomes unresponsive.
Your job is to investigate the issue and ensure satellite server is working properly.

== Objectives

* Investigate why web ui is not accessible and satellite becomes unresponsive occasionally in Red Hat Satellite 6.
* Investigate why widgets on Satellite web ui are not loading.
* Investigate why candlepin is down and some commands may fail to execute.
* Solve the functionality and performance issues in the hands-on lab environment.

== Recreate Scenario

To recreate this scenario, run the `lab` script on `bastion` server.

[source,bash,role=execute]
----
lab break breakfix2
----

.Sample output
----
[lab-user@bastion ~]$ lab break breakfix2
Initiating /usr/local/bin/lab with option(s) break breakfix2
Completed /usr/local/bin/lab with option(s) break breakfix2 successfully
----

[NOTE]
It may take 5-10 minutes to complete.

== Success Criteria

Ensure you are able to login to satellite web ui and see all widgets. You can verify it by running `hammer ping` command.

.Sample Output:
----
[root@satellite ~]# hammer ping
database:
    Status:          ok
    Server Response: Duration: 0ms
cache:
    servers:
     1) Status:          ok
        Server Response: Duration: 0ms
candlepin:
    Status:          ok
    Server Response: Duration: 16ms
candlepin_auth:
    Status:          ok
    Server Response: Duration: 14ms
candlepin_events:
    Status:          ok
    message:         0 Processed, 0 Failed
    Server Response: Duration: 0ms
katello_events:
    Status:          ok
    message:         0 Processed, 0 Failed
    Server Response: Duration: 0ms
pulp3:
    Status:          ok
    Server Response: Duration: 166ms
pulp3_content:
    Status:          ok
    Server Response: Duration: 35ms
foreman_tasks:
    Status:          ok
    Server Response: Duration: 2ms
----